export type Status = "Verified" | "Pending" | "Flagged" | "Submitted" | "Scheduled";
export type SyncStatus = "Synced" | "Offline Sync Pending" | "Failed" | "Not submitted";

export type Inspection = {
  id: string;
  organization: string;
  organizationId: string;
  location?: string;
  inspector: string;
  date: string;
  time: string;
  scheduledTime: string;
  gps: "Verified" | "Outside radius" | "Pending";
  photo: "Captured" | "Pending";
  status: Status;
  sync: SyncStatus;
  duration: string;
  distance: string;
  coordinates: string;
  evidenceId: string;
  photoMediaId?: string | null;
  photoUrl?: string | null;
  isLive?: boolean;
  isPersisted?: boolean;
  isScheduleOnly?: boolean;
  scheduleId?: string | null;
  locationCapturedAt?: string | null;
  photoCapturedAt?: string | null;
  submittedAt?: string | null;
  locationAccuracyM?: number | null;
  locationDistanceM?: number | null;
  locationCheckStatus?: string | null;
  notes?: string | null;
};
