"""Fictional portal demo payload stored in SQLite on first startup."""

PORTAL_DEMO_DATA = {
    "mapRadiusM": 100,
    "dashboard": {
        "updatedAt": "27 Sep 2026 · 11:05",
        "totalOrganizations": 248,
        "activeDistricts": 12,
        "inspectionsThisMonth": 86,
        "monthlyChange": "+12% from August",
        "verifiedInspections": 72,
        "verificationRate": "83.7% verification rate",
        "pendingVerification": 9,
        "flaggedInspections": 5,
        "offlineSyncPending": 3,
    },
    "inspections": [
        {"id": "SD-INS-2026-0842", "organization": "Seva Foundation", "organizationId": "seva-foundation", "inspector": "Aarav Mehta", "date": "27 Sep 2026", "time": "09:42", "gps": "Verified", "photo": "Captured", "photoMediaId": "demo-inspection-photo", "status": "Verified", "sync": "Synced", "duration": "48 min", "distance": "18 m", "coordinates": "28.6139° N, 77.2090° E", "evidenceId": "EV-842-A7F", "scheduledTime": "27 Sep · 08:00–11:00"},
        {"id": "SD-INS-2026-0841", "organization": "Udaan Welfare Society", "organizationId": "udaan-welfare", "inspector": "Meera Nair", "date": "27 Sep 2026", "time": "08:15", "gps": "Verified", "photo": "Captured", "photoMediaId": "demo-inspection-photo", "status": "Pending", "sync": "Synced", "duration": "52 min", "distance": "24 m", "coordinates": "28.5355° N, 77.3910° E", "evidenceId": "EV-841-K2C", "scheduledTime": "27 Sep · 07:00–10:00"},
        {"id": "SD-INS-2026-0838", "organization": "Jan Kalyan Trust", "organizationId": "jan-kalyan", "inspector": "Vikram Singh", "date": "26 Sep 2026", "time": "15:30", "gps": "Outside radius", "photo": "Captured", "photoMediaId": "demo-inspection-photo", "status": "Flagged", "sync": "Synced", "duration": "31 min", "distance": "184 m", "coordinates": "28.7041° N, 77.1025° E", "evidenceId": "EV-838-P9D", "scheduledTime": "26 Sep · 13:00–17:00"},
        {"id": "SD-INS-2026-0836", "organization": "Shakti Rural Development Centre", "organizationId": "shakti-rural", "inspector": "Nisha Verma", "date": "26 Sep 2026", "time": "12:10", "gps": "Verified", "photo": "Captured", "photoMediaId": "demo-inspection-photo", "status": "Verified", "sync": "Offline Sync Pending", "duration": "1 hr 04 min", "distance": "12 m", "coordinates": "28.4595° N, 77.0266° E", "evidenceId": "EV-836-M4J", "scheduledTime": "26 Sep · 09:00–13:00"},
        {"id": "SD-INS-2026-0831", "organization": "Hope Community Foundation", "organizationId": "hope-community", "inspector": "Rohan Kapoor", "date": "25 Sep 2026", "time": "10:05", "gps": "Verified", "photo": "Pending", "photoMediaId": None, "status": "Pending", "sync": "Offline Sync Pending", "duration": "44 min", "distance": "35 m", "coordinates": "28.4089° N, 77.3178° E", "evidenceId": "EV-831-Q5S", "scheduledTime": "25 Sep · 08:00–12:00"},
    ],
    "organizations": [
        {"id": "seva-foundation", "name": "Seva Foundation", "reg": "NGO-DL-2018-0421", "location": "New Delhi", "address": "Sector 14 Community Centre, New Delhi", "last": "27 Sep 2026", "next": "Window assigned", "verification": "Verified", "risk": "Low attention", "count": 24},
        {"id": "udaan-welfare", "name": "Udaan Welfare Society", "reg": "NGO-UP-2020-1178", "location": "Noida, Uttar Pradesh", "address": "Sector 14 Community Centre, Noida, Uttar Pradesh", "last": "27 Sep 2026", "next": "Review pending", "verification": "Pending", "risk": "Review", "count": 16},
        {"id": "jan-kalyan", "name": "Jan Kalyan Trust", "reg": "NGO-DL-2016-0892", "location": "North Delhi", "address": "Sector 14 Community Centre, North Delhi", "last": "26 Sep 2026", "next": "Randomized", "verification": "Flagged", "risk": "High attention", "count": 31},
        {"id": "shakti-rural", "name": "Shakti Rural Development Centre", "reg": "NGO-HR-2019-0634", "location": "Gurugram, Haryana", "address": "Sector 14 Community Centre, Gurugram, Haryana", "last": "26 Sep 2026", "next": "Sync pending", "verification": "Verified", "risk": "Low attention", "count": 19},
        {"id": "hope-community", "name": "Hope Community Foundation", "reg": "NGO-UP-2021-1430", "location": "Greater Noida, Uttar Pradesh", "address": "Sector 14 Community Centre, Greater Noida, Uttar Pradesh", "last": "25 Sep 2026", "next": "Not scheduled", "verification": "Pending", "risk": "Review", "count": 12},
    ],
    "analytics": [
        {"day": "1 Sep", "total": 8, "verified": 6, "pending": 2, "random": 3, "flagged": 0},
        {"day": "5 Sep", "total": 12, "verified": 9, "pending": 3, "random": 5, "flagged": 1},
        {"day": "9 Sep", "total": 10, "verified": 8, "pending": 2, "random": 4, "flagged": 1},
        {"day": "13 Sep", "total": 16, "verified": 13, "pending": 3, "random": 7, "flagged": 0},
        {"day": "17 Sep", "total": 13, "verified": 11, "pending": 2, "random": 6, "flagged": 1},
        {"day": "21 Sep", "total": 15, "verified": 12, "pending": 3, "random": 8, "flagged": 2},
        {"day": "27 Sep", "total": 12, "verified": 10, "pending": 2, "random": 5, "flagged": 0},
    ],
    "randomSchedule": [
        {"id": "RS-219", "organization": "Hope Community Foundation", "inspector": "Rohan Kapoor", "window": "28 Sep · 08:00–12:00", "frequency": "Quarterly", "state": "Upcoming"},
        {"id": "RS-218", "organization": "Jan Kalyan Trust", "inspector": "Vikram Singh", "window": "28 Sep · 13:00–17:00", "frequency": "Monthly", "state": "Upcoming"},
        {"id": "RS-214", "organization": "Seva Foundation", "inspector": "Aarav Mehta", "window": "27 Sep · 08:00–11:00", "frequency": "Quarterly", "state": "Completed"},
        {"id": "RS-211", "organization": "Udaan Welfare Society", "inspector": "Meera Nair", "window": "26 Sep · 09:00–13:00", "frequency": "Bi-monthly", "state": "Completed"},
    ],
    "randomScheduleStats": {
        "upcoming": 12,
        "districts": 8,
        "completedThisMonth": 34,
        "completionRate": "39.5% of inspections",
        "monthlyFrequency": 18,
        "nextGeneration": "18:00",
        "status": "Active",
    },
    "timeline": [
        {"title": "Random inspection scheduled", "time": "26 Sep 2026 · 18:00", "detail": "System-generated time window"},
        {"title": "Inspector notified", "time": "27 Sep 2026 · 08:02", "detail": "Assignment delivered securely"},
        {"title": "Inspector reached location", "time": "27 Sep 2026 · 09:39", "detail": "Arrival registered"},
        {"title": "GPS detected", "time": "27 Sep 2026 · 09:40", "detail": "Within 18 m of registered location"},
        {"title": "Live photo captured", "time": "27 Sep 2026 · 09:42", "detail": "Captured during inspection"},
        {"title": "Inspection completed", "time": "27 Sep 2026 · 10:30", "detail": "Digital record submitted"},
        {"title": "Evidence synchronized", "time": "27 Sep 2026 · 10:31", "detail": "Secure upload completed"},
        {"title": "Authority reviewed record", "time": "27 Sep 2026 · 11:05", "detail": "Evidence layers verified"},
    ],
    "cameras": [
        {"name": "Entrance Camera 01", "org": "Seva Foundation", "status": "Online", "last": "Live now", "timestamp": "27-09-2026 · 12:22 IST"},
        {"name": "Learning Centre 02", "org": "Udaan Welfare Society", "status": "Online", "last": "Live now", "timestamp": "27-09-2026 · 12:23 IST"},
        {"name": "Main Hall Camera", "org": "Jan Kalyan Trust", "status": "Offline", "last": "18 minutes ago", "timestamp": "27-09-2026 · 12:24 IST"},
        {"name": "Resource Centre 01", "org": "Shakti Rural Development Centre", "status": "Online", "last": "Live now", "timestamp": "27-09-2026 · 12:25 IST"},
    ],
    "sync": {
        "pendingUploads": 3,
        "pendingEvidenceFiles": 16,
        "synchronizedThisMonth": 81,
        "failedSynchronizations": 1,
        "lastSyncTime": "11:58",
        "lastSyncDate": "27 Sep 2026",
        "queuedRecords": 3,
        "queuedEvidenceSize": "46.2 MB",
        "progress": 64,
        "automaticRetry": True,
        "connectionStatus": "Available",
        "networkLabel": "Secure network · Stable",
    },
    "reports": {
        "totalInspections": 86,
        "organizationsInspected": 64,
        "coverage": "25.8% coverage",
        "randomInspections": 34,
        "randomShare": "39.5% of total",
        "offlineInspections": 11,
        "offlineSynchronized": 10,
        "pie": [
            {"name": "Verified", "value": 72, "color": "var(--success)"},
            {"name": "Pending", "value": 9, "color": "var(--warning)"},
            {"name": "Flagged", "value": 5, "color": "var(--destructive)"},
        ],
    },
    "settings": {
        "displayName": "Authority Officer",
        "oversightUnit": "Central Oversight Unit",
        "criticalInspectionAlerts": True,
        "automaticSynchronization": True,
    },
}

DEMO_ACCOUNTS = (
    ("authority", "authority", "Authority Officer", "satark123"),
    ("inspector", "inspector", "Inspector", "satark123"),
)
